package eu.dime.mobile.helper.objects;

public abstract class ResultObject {
	
	public enum RESULT_OBJECT_TYPES {
		SHARING_PROFILE, SHARING_PERSONS, SHARING_GROUPS, SHARING_DATABOXES, SHARING_RESOURCES, SHARING_LIVEPOSTS, 
		SERVICE_CONNECTION, ADD_RESOURCES_TO_DATABOX, ASSIGN_RESOURCES_TO_DATABOX, ADD_PEOPLE_TO_GROUP, ASSIGN_PEOPLE_TO_GROUP;
	};
	
	protected RESULT_OBJECT_TYPES type;
	
	public RESULT_OBJECT_TYPES getType() {
		return type;
	}
	
}
